/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./viewer.html", "./viewer.js", "./popup.html"],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "surface-container-low": "#1b1c1d",
              "on-tertiary-container": "#3a260c",
              "primary": "#b6c8de",
              "outline-variant": "#43474c",
              "secondary-fixed": "#eaddff",
              "inverse-primary": "#4e6073",
              "on-surface": "#e4e2e3",
              "primary-container": "#8093a7",
              "surface-container-highest": "#343536",
              "surface": "#131315",
              "outline": "#8e9196",
              "on-secondary-fixed-variant": "#4c4163",
              "surface-tint": "#b6c8de",
              "surface-container-high": "#292a2b",
              "surface-bright": "#39393a",
              "on-primary": "#203243",
              "surface-variant": "#343536",
              "secondary-container": "#4f4366",
              "on-tertiary": "#412c12",
              "on-surface-variant": "#c4c6cc",
              "on-error-container": "#ffdad6",
              "tertiary-fixed-dim": "#e3c19c",
              "secondary-fixed-dim": "#cfc0e9",
              "on-background": "#e4e2e3",
              "on-tertiary-fixed": "#291802",
              "on-primary-fixed-variant": "#37485a",
              "on-primary-fixed": "#0a1d2d",
              "error-container": "#93000a",
              "on-secondary": "#352b4c",
              "inverse-on-surface": "#303032",
              "background": "#131315",
              "on-primary-container": "#192b3c",
              "surface-container": "#1f2021",
              "primary-fixed": "#d2e4fb",
              "surface-dim": "#131315",
              "primary-fixed-dim": "#b6c8de",
              "tertiary-container": "#aa8b6a",
              "surface-container-lowest": "#0d0e0f",
              "on-secondary-container": "#c0b2da",
              "inverse-surface": "#e4e2e3",
              "on-secondary-fixed": "#201635",
              "tertiary-fixed": "#ffddb9",
              "on-error": "#690005",
              "tertiary": "#e3c19c",
              "error": "#ffb4ab",
              "secondary": "#cfc0e9",
              "on-tertiary-fixed-variant": "#5a4226"
      },
      "spacing": {
              "md": "16px",
              "lg": "24px",
              "xs": "8px",
              "sm": "12px",
              "container-max": "1440px",
              "base": "4px",
              "xl": "32px"
      },
      "fontFamily": {
              "sans": ['Inter', 'sans-serif'],
              "mono": ['JetBrains Mono', 'monospace'],
              "space": ['Space Grotesk', 'sans-serif'],
              "headline-xl": ["Inter"],
              "body-sm": ["Inter"],
              "headline-lg": ["Inter"],
              "body-md": ["Inter"],
              "data-mono": ["JetBrains Mono"],
              "headline-sm": ["Inter"],
              "label-caps": ["Inter"]
      },
      "fontSize": {
              "headline-xl": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "600"}],
              "body-sm": ["13px", {"lineHeight": "18px", "fontWeight": "400"}],
              "headline-lg": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
              "body-md": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
              "data-mono": ["13px", {"lineHeight": "18px", "fontWeight": "400"}],
              "headline-sm": ["18px", {"lineHeight": "24px", "fontWeight": "500"}],
              "label-caps": ["11px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600"}]
      }
    }
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
